### ISSUE TITLE
how to handle shared toString/ofString?

### ISSUE THREAD

**Issue by tcoopman** [yawaramin/fullstack-reason#2]
Currently your `ofString`/`toString` are very basic. How would you handle this in shared code if you wanted more complex shared messages. If I understand it correctly all the code/dependencies in shared have to work on the backend and with bucklescript. So using something like `Yojson` to serialize/de-serialize wouldn't work because that doesn't work on bucklescript AFAIK.

**Comment by yawaramin** [comment]
Good point. So a couple of days ago I moved ReWeb away from Ezjsonm to Yojson. Need to polish that up a little bit and update this project but, going forward, we should be able to use the `ppx_deriving_yojson` plugin to handle JSON on the backend and its BuckleScript port, https://github.com/ELLIOTTCABLE/bs-deriving , on the frontend.

In fact on the frontend you don't specifically need to use Yojson. Since JSON is standardized, you can use a different plugin like ppx_decco. The cool thing is, it can annotate the type along with Yojson:

```ocaml
type person { id : int; name : string }
[@@deriving yojson]
[@@decco]
```

And because the OCaml compiler ignores attributes it doesn't understand, Yojson and Decco should (I haven't tested this yet) work on the backend and frontend respectively, automatically.

Of course the caveat here is not trying to encode too-fancy stuff like tuples and such.

**Comment by tcoopman** [comment]
I'm actually trying it with `atd` at the moment, and I've got it working to share something between bucklescript and native. 

I'm not yet 100% happy with it yet, but it's working already, so that's something at least.

**Comment by yawaramin** [comment]
OK cool, let me know how it goes. Seems like you're building something interesting :-)

**Comment by tcoopman** [comment]
For now, I'm mostly playing around and experimenting. I'd like to see what is possible and how easy it is. It would be amazing if OCaml had a great web experience, and re-web certainly looks like something that goes in the right direction.

**Comment by yawaramin** [comment]
Btw I've now implemented asymmetric JSON encoding/decoding for the same type using ppx_deriving_yojson (backend) and decco (frontend). Works exactly as expected.
